name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check style
      run: cargo fmt -- --check

    # this will report success even if there are warnings, and should be manually checked for now
    - name: Lint
      run: cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Run unit tests
      run: cargo test --verbose

    - name: Run end-to-end tests
      run: test/e2e_test.sh

    - name: Build aarch64-apple-darwin
      run: |
        curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ
        export SDKROOT=$(pwd)/MacOSX13.3.sdk/
        export PATH=$PATH:~/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin/
        export CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=rust-lld
        rustup target add aarch64-apple-darwin
        cargo build --verbose --release --target aarch64-apple-darwin

    - name: Build x86_64-pc-windows-gnu
      run: |
        apt-get update && apt-get install -y mingw-w64
        rustup target add x86_64-pc-windows-gnu
        cargo build --verbose --release --target x86_64-pc-windows-gnu
