name: Rust

on:
  push:
    branches: [ develop, test-aarch-linux]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check style
      run: cargo fmt -- --check

    # this will report success even if there are warnings, and should be manually checked for now
    - name: Lint
      run: cargo clippy

    - name: Build
      run: cargo build --verbose

    - name: Run unit tests
      run: cargo test --verbose

    - name: Run end-to-end tests
      run: test/e2e_test.sh

    - name: Build aarch64-unknown-linux-gnu
      run: |
        rustup target add aarch64-unknown-linux-gnu
        cargo build --verbose --release --target aarch64-unknown-linux-gnu
